### ISSUE TITLE
Crawlers should support parsing CSV

### ISSUE THREAD

**Issue by ekryski** [tether/roach#13]

**Comment by bredele** [comment]
It's done.

``` js
crawler('path/to/file')
  .use(crawler.csv());
```

**Comment by ekryski** [comment]
I looked at the last few commits. Coming along quite nicely. Do you want to pair a bit on Friday?

**Comment by bredele** [comment]
I'll tell you that tomorrow. I'm in lethbridge right now but I'll go to calgary or edmonton friday.
Working with streams can be really confusing but it's pretty nice.
