### ISSUE TITLE
Crawlers should support parsing XLS/XLSX

### ISSUE THREAD

**Issue by ekryski** [tether/roach#14]

**Comment by bredele** [comment]
It's done. I'm using the libraries xls and xlsx from https://github.com/SheetJS. They look stable and pretty legit.

The handlers xls and xlsx transform a readable stream into an xls-array. It's then up to the developer to parse this data.

**Comment by ekryski** [comment]
Nice fucking find man! Those are the best xls libs so far

**Comment by bredele** [comment]
Great :) the crawler has everything you requested (xlm, html, csv, zip, xls/xlsx).
