### ISSUE TITLE
Crawler has a separate process

### ISSUE THREAD

**Issue by bredele** [tether/roach#19]
A job/crawler should/could run on separate processes. It means that the only way to communicate with the roach server will be through redis (start, stop, log, progress, data, etc). A job is instantiated once because ideally it'll always be alive.
- it should listen events coming from roach (pub/sub redis?)
- it should send events to roach (pub/sub redis?)
  > Global pub/sub channel or prefixed by job id?
- it should be initialized with job id and options (job start and job config?)
- it should send data (redis queue?)

**Comment by ekryski** [comment]
Ya this all looks good. I would say just use the global pub/sub channel for now.

**Comment by bredele** [comment]
It's done :) it's woking really well, you have an example in the `example` folder (you should start `stocks` in a separate shell to see it's working).

**Comment by ekryski** [comment]
k I'll pull it down right now :smile:

**Comment by bredele** [comment]
I tried to make a code as clean as possible so you should be able to understand how it's working just by reading it.
