### ISSUE TITLE
Create crawler.stop() method

### ISSUE THREAD

**Issue by ekryski** [tether/roach#23]
This is an alias for `.on('end')`.

**Comment by bredele** [comment]
I implemented a `end` handler but it's not really clean:

``` js
crawler()
  .pipe(crawler.end(cb));
```

I think it's not worth and we should instead use:

``` js
crawler()
  .on('end', cb);
```

or through:

``` js
crawler()
  .pipe(crawler.through(null, cb));
```

**Comment by ekryski** [comment]
Really? I kind of like your `crawler.pipe(crawler.end(cb))` but if not then use `crawler.on('end', cb);`

**Comment by bredele** [comment]
Ok we can keep it, here's the implementation:

``` js
Crawler.end = function(cb) {
  return this.through(null, cb);
};
```

Easy as pie!
