### ISSUE TITLE
Asynchronous goodness with co

### ISSUE THREAD

**Issue by bredele** [tether/roach#29]
@ekryski what do you think of?

``` js
var thunk = require('thunkify');
var redis = require('redis');
var db = redis.createClient();
var co = require('co');

db.set = thunk(db.set);
db.get = thunk(db.get);

co(function *(){
  yield db.set('foo', 'bar');
  yield db.set('bar', 'baz');

  var res = yield db.get('foo');
  console.log('foo -> %s', res);

  var res = yield db.get('bar');
  console.log('bar -> %s', res);
})()

```

**Comment by bredele** [comment]
It would be really great for roach :+1:

**Comment by ekryski** [comment]
What is this for? I'd have to look into the thunkify lib to see what it does. Can you give me a bit more detail for what you were thinking of using ES6 generators for and the problem its solving?

**Comment by bredele** [comment]
Basically generators (functions that contains the keyword yield) allow you to define sequences/iterations into a single function:

``` js
function generator() {
  yield 'olivier';
  yield 'eric';
}

var gen = generator();
gen,next(); // => {value:'olivier'}
gen.next(); // = > {value:'eric'}
```

It's also pretty neat to deal with asynchronous stuff and avoid callbacks cascading . Here's an example with redis:

``` js
client.incr(name, function(err, id){
  client.add(id, function(err, res) {
    client.hset(id, value, function(err, res) {
      //do something 
   });
  });
});
```

and with generators and thunks using the library co:

``` js
co(function *(){
  var id = yield client.incr(name);
  yield client.add(id);
  yield client.hset(id, value);
})();
```

co basically do the `next` for you and force you to yield functions/promises or thunks in order to format the returned values and to handle exceptions.
A thunk is just a functional trick to pass some arguments to a function but delay its execution until you pass a callback.

``` js
var read = function(name, encoding) {
  return function (cb){
    readFile(name, encoding, cb);
  };
};
```

**Comment by bredele** [comment]
It's part of Javascript 1.7 and works on nodejs 0.11.9. It's worth looking at just for general culture.

**Comment by ekryski** [comment]
Ya I know how generators work and that they are supported. It's good to keep up to date but for now I want to keep roach with minimal new stuff until we have everything nailed down. I need the other guys in the company to be able to understand it as well.

**Comment by ekryski** [comment]
So I would say "maybe" in the future but for now let's not bring in generators just yet.

**Comment by bredele** [comment]
ok sure.
