### ISSUE TITLE
Get available crawlers via REST API

### ISSUE THREAD

**Issue by ekryski** [tether/roach#5]
In order to schedule jobs #4, we need to be able to see what jobs are available to be scheduled. We need a REST endpoint to do this. `GET /crawlers`

**Comment by bredele** [comment]
Eric, I close the issue and you could reopen it on step 2, is it ok?

**Comment by ekryski** [comment]
Not let's open it now and just put assign it to the Phase 2 milestone.

**Comment by ekryski** [comment]
I think it is already assigned to that actually. Just filter your issues to only show phase 1

**Comment by bredele** [comment]
I don't see any issues assigned to the milestone 1.
