### ISSUE TITLE
We should have a way to run the roach server

### ISSUE THREAD

**Issue by ekryski** [tether/roach#8]
If we do `npm install -g roach` we should then be able to simply run the server in two ways:
1. CLI:

`
roach run --port 5000 --crawlers /users/eric/dev/crawlers
`
2. In our own custom js file:

``` js
var roach = require('roach').server({
  port: 5000,
  crawlers: './crawlers'
});

// Do some stuff.

roach.run();
```

**Comment by bredele** [comment]
```
roach run -r
```

the `-r --redis` option allows you to configure a redis client (port, host) with a nice and easy prompt.
