### ISSUE TITLE
Data from crawler should be shipped off to RabbitMQ

### ISSUE THREAD

**Issue by ekryski** [tether/roach#9]
All data that is finished being processed should be shipped in JSON form to RabbitMQ.

**Comment by bredele** [comment]
Right now a job send data to redis through the channel `roach:job:$id:data`. We have to create a job that subscribe to this channel and send the data to RabbitMQ:

``` js
roach()
  .use(rabbit)
```

**Comment by ekryski** [comment]
:thumbsup:

**Comment by bredele** [comment]
It'll be the same with the scheduler which will have its own queue.

**Comment by ekryski** [comment]
We should also have the ability to pass config options when "using" the transport. These options will eventually come from env vars or a config file.

``` js
roach.use('rabbit', {
 host: '127.0.0.1',
 port: 15672
});
```

**Comment by ekryski** [comment]
This is now working but needs cleanup and tests.
